In [2]:
import os
import pandas as pd

In [3]:
%load_ext autoreload
%autoreload 2

In [4]:
os.chdir('C:/Users/basleal/Desktop/tutorial/kaim-week-8-9')
print(os.getcwd())

C:\Users\basleal\Desktop\tutorial\kaim-week-8-9

In [5]:
path = 'data/fraud_data_final.csv'
path_2 = 'data/creditcard.csv'
fraud_data=pd.read_csv(path)
credit_data=pd.read_csv(path_2)

In [6]:
fraud_data['signup_time'] = pd.to_datetime(fraud_data['signup_time'])
fraud_data['purchase_time'] = pd.to_datetime(fraud_data['purchase_time'])

In [7]:
credit_data

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [8]:
fraud_data

,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,user_id,signup_time,purchase_time,purchase_value,device_id,source,browser,...,country,time_diff_hours,transaction_count,hour_of_day,day_of_week,purchase_value_scaled,time_diff_hours_scaled,browser_encoded,sex_encoded,age_encoded
0,0,0,0,22058,2015-02-24 22:55:49,2015-04-18 02:47:11,34,QVPSPJUOCKZAR,SEO,Chrome,...,Japan,1251.856111,1,2,5,0.172414,0.434673,0,1,21
1,1,1,1,333320,2015-06-07 20:39:50,2015-06-08 01:38:54,16,EOGFQPIZPYXFZ,Ads,Chrome,...,United States,4.984444,1,1,0,0.048276,0.001731,0,0,35
2,2,2,2,1359,2015-01-01 18:52:44,2015-01-01 18:52:45,15,YSSKYOSJHPPLJ,SEO,Opera,...,United States,0.000278,1,18,3,0.041379,0.000000,3,1,35
3,3,3,3,150084,2015-04-28 21:13:25,2015-05-04 13:54:50,44,ATGTXKYKUDUQN,SEO,Safari,...,Unknown,136.690278,1,13,0,0.241379,0.047462,4,1,23
4,4,4,4,221365,2015-07-21 07:09:52,2015-09-09 18:40:53,39,NAUITBZFJKHWW,Ads,Safari,...,United States,1211.516944,1,18,2,0.206897,0.420667,4,1,27
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151107,151107,151107,151107,345170,2015-01-27 03:03:34,2015-03-29 00:30:47,43,XPSKTWGPWINLR,SEO,Chrome,...,United States,1461.453611,1,0,6,0.234483,0.507450,0,1,10
151108,151108,151108,151108,274471,2015-05-15 17:43:29,2015-05-26 12:24:39,35,LYSFABUCPCGBA,SEO,Safari,...,Netherlands,258.686111,1,12,1,0.179310,0.089822,4,1,14
151109,151109,151109,151109,368416,2015-03-03 23:07:31,2015-05-20 07:07:47,40,MEQHCSJUBRBFE,SEO,IE,...,Japan,1856.004444,1,7,2,0.213793,0.644448,2,0,8
151110,151110,151110,151110,207709,2015-07-09 20:06:07,2015-09-07 09:34:46,46,CMCXFGRHYSTVJ,SEO,Chrome,...,United States,1429.477500,1,9,0,0.255172,0.496348,0,1,19
151111,151111,151111,151111,138208,2015-06-10 07:02:20,2015-07-21 02:03:53,20,ZINIADFCLHYPG,Direct,IE,...,Unknown,979.025833,1,2,1,0.075862,0.339940,2,1,20

In [9]:
from sklearn.model_selection import train_test_split
x_credit_card = credit_data.drop(columns='Class')
y_credit_card = credit_data['Class']

In [18]:
x_fraud_data = fraud_data.drop(columns=['class','device_id','user_id','source', 'browser', 'sex','country','Unnamed: 0','Unnamed: 0.1','Unnamed: 0.2','signup_time','purchase_time'])
y_fraud_data = fraud_data['class']
x_train_fraud,x_test_fraud, y_train_fraud, y_test_fraud = train_test_split(x_fraud_data,y_fraud_data,test_size=0.2,random_state=42)

In [19]:
x_fraud_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 12 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   purchase_value          151112 non-null  int64
 1   age                     151112 non-null  int64
 2   ip_address              151112 non-null  float64
 3   time_diff_hours         151112 non-null  float64
 4   transaction_count       151112 non-null  int64
 5   hour_of_day             151112 non-null  int64
 6   day_of_week             151112 non-null  int64
 7   purchase_value_scaled   151112 non-null  float64
 8   time_diff_hours_scaled  151112 non-null  float64
 9   browser_encoded         151112 non-null  int64
 10  sex_encoded             151112 non-null  int64
 11  age_encoded             151112 non-null  int64
dtypes: float64(4), int64(8)
memory usage: 13.8 MB

In [15]:
y_train_fraud.value_counts()

class
0    109588
1     11301
Name: count, dtype: int64

In [12]:
fraud_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151112 entries, 0 to 151111
Data columns (total 24 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Unnamed: 0.2            151112 non-null  int64
 1   Unnamed: 0.1            151112 non-null  int64
 2   Unnamed: 0              151112 non-null  int64
 3   user_id                 151112 non-null  int64
 4   signup_time             151112 non-null  datetime64[ns]
 5   purchase_time           151112 non-null  datetime64[ns]
 6   purchase_value          151112 non-null  int64
 7   device_id               151112 non-null  object
 8   source                  151112 non-null  object
 9   browser                 151112 non-null  object
 10  sex                     151112 non-null  object
 11  age                     151112 non-null  int64
 12  ip_address              151112 non-null  float64
 13  class                   151112 non-null  int64
 14  country                 151112 non-null  object
 15  time_diff_hours         151112 non-null  float64
 16  transaction_count       151112 non-null  int64
 17  hour_of_day             151112 non-null  int64
 18  day_of_week             151112 non-null  int64
 19  purchase_value_scaled   151112 non-null  float64
 20  time_diff_hours_scaled  151112 non-null  float64
 21  browser_encoded         151112 non-null  int64
 22  sex_encoded             151112 non-null  int64
 23  age_encoded             151112 non-null  int64
dtypes: datetime64[ns](2), float64(4), int64(13), object(5)
memory usage: 27.7+ MB

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from scripts.model_building import logistic_regression
model_1 = logistic_regression(x_train_fraud,y_train_fraud,x_test_fraud,y_test_fraud)
print(model_1)

[1 1 0 ... 0 0 0]

:

In [1]:
pd.Series(model_1).value_counts

NameError: name 'pd' is not defined

In [12]:
import tensorflow